on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connected
      run: echo "Connected to the VM."
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 
        "sudo docker ps -a"
    - name: Clone the repo
      run: "git clone https://github.com/xB0t/Django-Weather-App.git"
    - name: Change into Django Weather App Directory
      run: "cd Django-Weather-App/"
    - name: Build Docker Image.
      # run: "docker build -t django-weather-app ."
      run: sudo docker build .
      
    - name: cleanup
      run: rm -rf ~/.ssh
#cd ${{ secrets.WORK_DIR }}
